### ISSUE TITLE
Editing non-existent profile causes traceback

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#16]
https://github.com/candlepin/rho/issues/10

if we try to "rho profile edit" a profile that doesnt exist:
```
Traceback (most recent call last):
File "/home/adrian/src/rho/bin/rho", line 22, in
CLI().main()
File "/home/adrian/src/rho/src/rho/cli.py", line 95, in main
cmd.main()
File "/home/adrian/src/rho/src/rho/clicommands.py", line 136, in main
self._do_command()
File "/home/adrian/src/rho/src/rho/clicommands.py", line 461, in _do_command
g.ranges = self.options.ranges
AttributeError: 'NoneType' object has no attribute 'ranges'
```

**Comment by chambridge** [comment]
A trace back does not occur, but we incorrectly state:
```
$ rho profile edit --name=not_a_profile --hosts 192.168.50.[10:12] --auth test
Auths do not exist.
```
Current control flow sets both profile and auth to does not exist. Checks for profile and if found checks for auth. If profile doesn't exist it doesn't change the state of auth even if it does exist. Problem is it prints info about Auth does not exist first. Need to update error information flow.
