### ISSUE TITLE
rho profile add does not validate sshport option

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#175]
`rho profile add` should first validate if the `sshport` option is an integer before trying to convert to int. The user should be properly notified if a non-integer value is provided with an error message, instead of a stacktrace being output.

```console
$ rho profile add --name 1 --hosts 127.0.0.1 --auth 1 --sshport string
Please enter your rho vault password: 
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/camayoc/bin/rho", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/elyezer/code/rho/bin/rho", line 28, in <module>
    CLI().main()
  File "/home/elyezer/code/rho/rho/cli.py", line 124, in main
    cmd.main()
  File "/home/elyezer/code/rho/rho/clicommand.py", line 91, in main
    self._do_command()
  File "/home/elyezer/code/rho/rho/profileaddcommand.py", line 112, in _do_command
    ssh_port = utilities.validate_port(self.options.sshport)
  File "/home/elyezer/code/rho/rho/utilities.py", line 188, in validate_port
    arg = int(arg)
ValueError: invalid literal for int() with base 10: 'string'
```

## Specify type:
- Enhancement

### Version of rho:
0f712e713a53753928e64d89319edb6e68c34c05

**Comment by elyezer** [comment]
The validation should also cover the case when it is outside the expected range, instead of outputting this stacktrace:

```console
rho profile add --name 1 --hosts 127.0.0.1 --auth 1 --sshport 999999
Please enter your rho vault password: 
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/camayoc/bin/rho", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/elyezer/code/rho/bin/rho", line 28, in <module>
    CLI().main()
  File "/home/elyezer/code/rho/rho/cli.py", line 124, in main
    cmd.main()
  File "/home/elyezer/code/rho/rho/clicommand.py", line 91, in main
    self._do_command()
  File "/home/elyezer/code/rho/rho/profileaddcommand.py", line 112, in _do_command
    ssh_port = utilities.validate_port(self.options.sshport)
  File "/home/elyezer/code/rho/rho/utilities.py", line 197, in validate_port
    raise ValueError('Port %s not in valid range (0-65535)' % arg)
ValueError: Port 999999 not in valid range (0-65535)
```
