### ISSUE TITLE
rho profile clear --name <name> fails when there is no data/profiles file

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#176]
RHO should provide an error message instead of outputting a Python stacktrace when trying to clear on profile and the profile data file is not created. Also it should return a non-zero exit code indicating that nothing was removed.

```console
$ ls data 
credentials

$ rho profile clear --name 1                             
Please enter your rho vault password: 
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/camayoc/bin/rho", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/elyezer/code/rho/bin/rho", line 28, in <module>
    CLI().main()
  File "/home/elyezer/code/rho/rho/cli.py", line 124, in main
    cmd.main()
  File "/home/elyezer/code/rho/rho/clicommand.py", line 91, in main
    self._do_command()
  File "/home/elyezer/code/rho/rho/profileclearcommand.py", line 70, in _do_command
    profiles_list = vault.load_as_json(utilities.PROFILES_PATH)
  File "/home/elyezer/code/rho/rho/vault.py", line 105, in load_as_json
    return json.loads(self.load_secure_file(secure_file).decode('UTF-8'))
  File "/home/elyezer/code/rho/rho/vault.py", line 98, in load_secure_file
    return self.load(open(secure_file).read())
FileNotFoundError: [Errno 2] No such file or directory: 'data/profiles'
```

## Specify type:
- Enhancement

### Version of rho:
45775d8e82b9f35eb6c9dd75fb44a1430915b5ec

**Comment by chambridge** [comment]
@elyezer Currently if you do the same with `rho auth clear --name 1` it will return 0 and state `All authorization credentials removed`. I plan to make it consistent with that interaction if that is fine with you.

**Comment by elyezer** [comment]
On the current version I have I tried with `rho auth clear --name 1` and does not output anything when the data dir is not created:

```console
$ rho auth clear --name 1
Please enter your rho vault password: 

$  $ rho profile clear --name 1
Please enter your rho vault password: 
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/camayoc/bin/rho", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/elyezer/code/rho/bin/rho", line 28, in <module>
    CLI().main()
  File "/home/elyezer/code/rho/rho/cli.py", line 124, in main
    cmd.main()
  File "/home/elyezer/code/rho/rho/clicommand.py", line 91, in main
    self._do_command()
  File "/home/elyezer/code/rho/rho/profileclearcommand.py", line 70, in _do_command
    profiles_list = vault.load_as_json(utilities.PROFILES_PATH)
  File "/home/elyezer/code/rho/rho/vault.py", line 105, in load_as_json
    return json.loads(self.load_secure_file(secure_file).decode('UTF-8'))
  File "/home/elyezer/code/rho/rho/vault.py", line 98, in load_secure_file
    return self.load(open(secure_file).read())
FileNotFoundError: [Errno 2] No such file or directory: 'data/profiles'

$ stat data
stat: cannot stat 'data': No such file or directory
```

I will pull the changes later and run that again to test it out.

**Comment by elyezer** [comment]
Here is the test I did after pulling 75a29c3:

```console
$ rho profile clear --name 1   
All network profiles removed

$ rho auth clear --name 1
Please enter your rho vault password: 

$ stat data
stat: cannot stat 'data': No such file or directory
```

They don't have the same behavior.

**Comment by chambridge** [comment]
Yep, I'll make sure they are consistent. I must have misread the code.
