### ISSUE TITLE
UnicodeEncodeError when writing CSV

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#495]
## Specify type:
- Bug

### Bug severity (if applicable):
- High

## Description:
```
Traceback (most recent call last):
  File "/usr/local/bin/rho", line 4, in <module>
    __import__('pkg_resources').run_script('rho==0.0.31', 'rho')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/rho-0.0.31-py2.7.egg/EGG-INFO/scripts/rho", line 28, in <module>
    
  File "build/bdist.macosx-10.12-x86_64/egg/rho/cli.py", line 137, in main
  File "build/bdist.macosx-10.12-x86_64/egg/rho/clicommand.py", line 87, in main
  File "build/bdist.macosx-10.12-x86_64/egg/rho/scancommand.py", line 287, in _do_command
  File "build/bdist.macosx-10.12-x86_64/egg/rho/inventory_scan.py", line 235, in inventory_scan
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 20: ordinal not in range(128)
```

**Comment by noahl** [comment]
I'm having trouble reproducing. When I scan the same hosts you did, I run into a different error. Do you have the exact command you ran?
