### ISSUE TITLE
Exception in thread Thread-2 (most likely raised during interpreter shutdown):

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#499]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
Did a fresh install of RHEL 6. Used updated install method which uses pip to update Jinja2. Ran a rho scan and got the following error. 

```
TASK [write : write the list to a csv] *****************************************
task path: /usr/share/ansible/rho/roles/write/tasks/main.yml:11
Using module file /usr/share/ansible/rho/library/spit_results.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
-- output truncated --
PLAY RECAP *********************************************************************
192.168.56.56              : ok=208  changed=68   unreachable=0    failed=0   
192.168.56.6               : ok=217  changed=76   unreachable=0    failed=0   
192.168.56.7               : ok=218  changed=77   unreachable=0    failed=0   
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
-- output truncated --
Scanning has completed. The mapping has been stored in file '/root/.config/rho/test1_host_auth_mapping'. The facts have been stored in '/root/out.csv'
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/usr/lib/python2.6/site-packages/rho/utilities.py", line 161, in tail_host_scan
  File "/usr/lib/python2.6/site-packages/sh.py", line 857, in next
  File "/usr/lib64/python2.6/Queue.py", line 174, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/usr/lib/python2.6/site-packages/rho/utilities.py", line 113, in tail_discovery_scan
  File "/usr/lib/python2.6/site-packages/sh.py", line 857, in next
  File "/usr/lib64/python2.6/Queue.py", line 174, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread background thread for pid 5989 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/usr/lib/python2.6/site-packages/sh.py", line 1540, in wrap
  File "/usr/lib/python2.6/site-packages/sh.py", line 2457, in background_thread
  File "/usr/lib/python2.6/site-packages/sh.py", line 2302, in is_alive
<type 'exceptions.TypeError'>: an integer is required
Exception in thread background thread for pid 6782 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/usr/lib/python2.6/site-packages/sh.py", line 1540, in wrap
  File "/usr/lib/python2.6/site-packages/sh.py", line 2457, in background_thread
  File "/usr/lib/python2.6/site-packages/sh.py", line 2302, in is_alive
<type 'exceptions.TypeError'>: an integer is required
```
___

### Version of rho:
0.0.30

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
Fresh RHEL 6.7 minimal-install
rpm -Uvh https://download.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
yum -y install rho
yum install python-devel python-pip
easy_install -U pycrypto
pip install -U Jinja2
rho auth add --name test1 --username root --password
rho profile add --name test1 --hosts 192.168.56.0/24 --auth test1
rho scan --profile=test1 --reportfile=out.csv -vvvv

### Environment information

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 6.7        | 2.6.6            | Virtual Box
Target System   | RHEL             | 7.x and 5.6

[root@rhel6 ~]# pip list | grep "Jinja2"
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Jinja2 (2.10)
[root@rhel6 ~]# pip list | grep "pycrypto"
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pycrypto (2.6.1)

**Comment by mdvickst** [comment]
[log_files.tar.gz](https://github.com/quipucords/rho/files/1521880/log_files.tar.gz)

**Comment by chambridge** [comment]
Just guessing here but this is probably a random failure from the log tailing:

threaded_tailing:
https://github.com/quipucords/rho/blob/master/rho/utilities.py#L87

tail_host_scan:
https://github.com/quipucords/rho/blob/master/rho/utilities.py#L145

Probably some try/catch is necessary here:
https://github.com/quipucords/rho/blob/master/rho/ansible_utils.py#L139

Basically this is the only spot we create another thread.
