### ISSUE TITLE
Traceback hit when running with basic user on non-JBoss system.

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#534]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
Traceback error hit when running full scan on a system with a non-sudo user and no JBoss installed.
___

### Version of rho:
[ 0.0.31 ]

### Expected behavior:
Scan should complete successfully.

### Actual behavior:
Traceback:
```
E         Traceback (most recent call last):
E           File "/home/elyezer/.virtualenvs/camayoc/bin/rho", line 6, in <module>
E             exec(compile(open(__file__).read(), __file__, 'exec'))
E           File "/home/elyezer/code/rho/bin/rho", line 28, in <module>
E             CLI().main()
E           File "/home/elyezer/code/rho/rho/cli.py", line 137, in main
E             cmd.main()
E           File "/home/elyezer/code/rho/rho/clicommand.py", line 87, in main
E             self._do_command()
E           File "/home/elyezer/code/rho/rho/scancommand.py", line 311, in _do_command
E             verbosity=self.verbosity)
E           File "/home/elyezer/code/rho/rho/inventory_scan.py", line 197, in inventory_scan
E             postprocessing.process_jboss_eap_home(facts_to_collect, host_vars))
E           File "/home/elyezer/code/rho/rho/postprocessing.py", line 669, in process_jboss_eap_home
E             for directory in eap_homes
E           File "/home/elyezer/code/rho/rho/postprocessing.py", line 670, in <listcomp>
E             if ls_results_mr[directory] or cat_results_mr[directory]]
E         KeyError: 'find: '/proc/31788': No such file or directory'
```
### Steps to reproduce:
Run scan with non-sudo user on system without JBoss installed using `--facts all`

**Comment by noahl** [comment]
Looks like this issue should have been closed when Chris' PR was merged. @chambridge can you confirm that this is done?

**Comment by chambridge** [comment]
This PR is not merged yet.
